twig:
    form_theme: ['bootstrap_4_layout.html.twig']

    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_path_jobs_images: '%env(string:UPLOAD_PATH_JOBS)%'
        app_path_projects_images: '%env(string:UPLOAD_PATH_PROJECTS)%'
        app_path_articles_images: '%env(string:UPLOAD_PATH_ARTICLES)%'
        app_path_default_images: '%env(string:UPLOAD_PATH_DEFAULT)%'

