vich_uploader:
    db_driver: orm

    mappings:
        project_images:
            uri_prefix:         '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_images%'

        job_images:
            uri_prefix:         '%app.path.job_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.job_images%'
