vich_uploader:
    db_driver: orm
    mappings:
        project_images:
            uri_prefix:         '%app.path.project_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.project_images%'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        job_images:
            uri_prefix:         '%app.path.job_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.job_images%'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

        article_images:
            uri_prefix:         '%app.path.article_images%'
            upload_destination: '/public%app.path.article_images%'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
