source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.0.1'
gem 'rspec'
gem 'capistrano'
gem 'capistrano-rvm', github: 'capistrano/rvm'
gem 'capistrano-rbenv'
gem 'capistrano-rails'
gem 'capistrano-chruby'
gem 'capistrano-passenger'
gem 'capistrano-composer'
gem 'capistrano-yarn'
