easy_admin:
  entities:
    Tags:
      class: App\Entity\Tag
      list:
        fields:
          - 'name'
          - 'slug'
          - 'articles'
      form:
        fields:
          - {property: 'name',type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'}
          - {property: 'slug'}